# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_url', models.CharField(max_length=400)),
                ('affiliate_url', models.CharField(max_length=400)),
                ('current_price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('specifications', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricehound_admin.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricehound_admin.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('capacity', models.CharField(max_length=50)),
                ('images', models.TextField()),
                ('best_current_price', models.CharField(max_length=20)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricehound_admin.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='productlisting',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricehound_admin.ProductModel'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricehound_admin.ProductVariant'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricehound_admin.Store'),
        ),
    ]
