# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehound_admin', '0002_remove_productlisting_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='capacity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
