# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehound_admin', '0003_auto_20171028_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='capacity',
            field=models.CharField(blank=True, default='64 GB', max_length=50),
            preserve_default=False,
        ),
    ]
