# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehound_admin', '0006_auto_20171029_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='listing_url',
            field=models.URLField(),
        ),
    ]
