# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehound_admin', '0007_auto_20171029_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='affiliate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain',
            field=models.URLField(),
        ),
    ]
