# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehound_admin', '0008_auto_20171029_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='affiliate_url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='listing_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together=set([('product_variant', 'store')]),
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together=set([('brand', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set([('product_model', 'color', 'capacity')]),
        ),
    ]
