# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehound_admin', '0011_productlisting_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='available',
        ),
        migrations.AddField(
            model_name='store',
            name='store_code',
            field=models.CharField(default='AM-IN', max_length=20),
            preserve_default=False,
        ),
    ]
